/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __GT_MARSHALS_MARSHAL_H__
#define __GT_MARSHALS_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* OBJECT: VOID (/data/code/graceful-terminator/app/gt-marshals.list:1) */
G_GNUC_INTERNAL
void gt_marshals_OBJECT__VOID (GClosure     *closure,
                               GValue       *return_value,
                               guint         n_param_values,
                               const GValue *param_values,
                               gpointer      invocation_hint,
                               gpointer      marshal_data);

/* VOID: ENUM (/data/code/graceful-terminator/app/gt-marshals.list:2) */
#define gt_marshals_VOID__ENUM	g_cclosure_marshal_VOID__ENUM

/* VOID: ENUM, STRING, BOOLEAN (/data/code/graceful-terminator/app/gt-marshals.list:3) */
G_GNUC_INTERNAL
void gt_marshals_VOID__ENUM_STRING_BOOLEAN (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID: UINT, UINT (/data/code/graceful-terminator/app/gt-marshals.list:4) */
G_GNUC_INTERNAL
void gt_marshals_VOID__UINT_UINT (GClosure     *closure,
                                  GValue       *return_value,
                                  guint         n_param_values,
                                  const GValue *param_values,
                                  gpointer      invocation_hint,
                                  gpointer      marshal_data);

/* VOID: VOID (/data/code/graceful-terminator/app/gt-marshals.list:5) */
#define gt_marshals_VOID__VOID	g_cclosure_marshal_VOID__VOID


G_END_DECLS

#endif /* __GT_MARSHALS_MARSHAL_H__ */
